services:
  postgres:
    image: postgres:latest
    container_name: pg
    deploy:
      resources:
        limits:
          cpus: '3'
    environment:
      PGUSER: goger
      POSTGRES_DB: goger
      POSTGRES_USER: goger
      POSTGRES_PASSWORD: goger
    volumes:
      # :z shut up about security when running go mod tidy
      - ./postgres-data:/var/lib/postgresql/data:z 
      - ./init-scripts:/docker-entrypoint-initdb.d
# Custom config
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "goger"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 2s 
    ports:
      - "5432:5432"
    networks:
      - db-network

  redis:
    image: redis:latest
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 2s
    networks:
      - redis-network

  fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fetcher
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db-network

  nginx:
    image: nginx:bookworm
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - fronter
    networks:
      - nginx-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx

  fronter:
    build:
      context: .
      dockerfile: Dockerfile-front
    container_name: fronter
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - db-network
      - redis-network
      - nginx-network

networks:
  db-network:
  redis-network:
  nginx-network:

volumes:
  nginx_logs:


