services:
  postgres:
    image: postgres:17.4-bookworm
    container_name: pg
    deploy:
      resources:
        limits:
          cpus: '2'
    environment:
      PGUSER: goger
      POSTGRES_DB: goger
      POSTGRES_USER: goger
      POSTGRES_PASSWORD: goger
    volumes:
      # :z shut up about security when running go mod tidy
      - ./postgres-data:/var/lib/postgresql/data:z 
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "goger", "-U", "goger"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 2s 
    ports:
      - "5432:5432"
    networks:
      - db-network

  fetcher:
    build:
      context: ./fetcher
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db-network

  fronter:
    build:
      context: ./front
    expose:
      - "8080"
    networks:
      - nginx-network

  nginx:
    image: nginx:1.27.4-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - fronter
    networks:
      - nginx-network

networks:
  db-network:
  nginx-network:

volumes:
  nginx_logs:
