FROM golang:1.21.3-alpine3.18 AS binary-builder
RUN apk update && apk upgrade
# && apk --update add upx
WORKDIR /builder
COPY go.mod go.sum *.go cmd ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 cd front && go build \
  -ldflags='-w -s -extldflags "-static"' -a \
  -o ../app
# For development there's no need for packer
# && upx -9 app

FROM gcr.io/distroless/static
WORKDIR /app
COPY static/ static/
COPY templates/ templates/
COPY --from=binary-builder --chown=nonroot:nonroot /builder/app .
ENTRYPOINT ["./app"]
