worker_processes 1;

events {
    worker_connections 256;
}

http {
    limit_req_zone $binary_remote_addr zone=one:10m rate=2r/s;

    server {
        listen 80;

        # Respond to all domains
        server_name _;

        keepalive_timeout 30;

        location / {
            limit_req zone=one burst=2 nodelay;
            proxy_pass http://fronter:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}